spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能

  datasource:
    url: jdbc:postgresql://localhost:5432/ztm_earth?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=true
    username: postgres
    password: 123.com
    driver-class-name: org.postgresql.Driver
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false
      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

mybatis-plus:
  mapper-locations: classpath:mybatis-plus/mapper/*.xml  #sql映射文件位置
  type-aliases-package: com.earth.domain
    # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中了。
    # config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true   # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将日志输出到控制台上

server:
  servlet:
    encoding:
      charset: utf-8 # 指定使用的编码方式
      force: true # 强制request,response都要使用
      enabled: true # 让系统的CharacterEncodingFilter生效
  port: 9000

